### ISSUE TITLE
`empv-playlist-select` not working with local files

### ISSUE THREAD

**Issue by qjcg** [isamert/empv.el#7] opened 2022-04-05 21:42 UTC
After enqueuing some entries into the playlist, calling `empv-playlist-select` interactively appears to do nothing. No playlist items are presented for selection. However, `empv-playlist-next` and `empv-playlist-prev` are working as expected.

UPDATE: After further testing, it seems `empv-playlist-select` IS working when there are YouTube results, but it does nothing when there are only local files in the playlist.

Using `mpv` 0.34.1 on macOS.

**Comment by isamert** [comment] 2022-04-06 22:47
I wasn't able to reproduce this on Linux, will try it on Mac soon. Meanwhile

- Can you do `M-x toggle-debug-on-error` and see if any error pops up after calling `empv-playlist-select`?
- Can you give me a step-by-step guide to reproduce this issue, from closed empv state (call `empv-exit` first to be sure) to where you called `empv-playlist-select`?
- Also, after queuing some stuff on playlist, send me the output of the following command:
  ```sh
  echo '{ "command": ["get_property", "playlist"] }' | socat - /tmp/empv-socket
  ```
  You need to have the `socat` program to be able to run this snippet. I believe you can install it with `brew install socat`.

Also does it only work with YouTube results or works with mixed results (YouTube and local files)?

**Comment by isamert** [comment] 2022-06-05 06:43
> I wasn't able to reproduce this on Linux, will try it on Mac soon.

I also was not able to reproduce this on Mac. Closing the issue for now, feel free to reopen if it's still happening.

**Closed by isamert** 2022-06-05 06:43 UTC
